# analisi dataset nasa c-mapss

In [1]:
import os 
os.chdir('/workspaces/my-project/')

In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

#Definiamo i nomi delle 26 colonne indicati nella documentazione pdf
nomi_colonne = ['id_motore','ciclo','altitudine','velocita_mach','manetta_tra','T2', 'T24', 'T30', 'T50', 'P2',
                 'P15', 'P30', 'Nf', 'Nc', 'epr','Ps30', 'phi', 'NRf', 'NRc','BPR','farB', 'htBleed', 'Nf_dmd', 
                 'PCNf_dmd','W31','W32'
]

# [span_4](start_span)Carichiamo il dataset usando il percorso calcolato nella cella precedente[span_4](end_span)
df_train = pd.read_csv('data/train_FD001.txt', sep=r'\s+', names=nomi_colonne)

# Mostriamo un riepilogo e la tabella interattiva ai tutor
print(f"Matrice C-MAPSS caricata correttamente! Formato: {df_train.shape} (Righe x Colonne)")
display(df_train.head())

Matrice C-MAPSS caricata correttamente! Formato: (20631, 26) (Righe x Colonne)

,id_motore,ciclo,altitudine,velocita_mach,manetta_tra,T2,T24,T30,T50,P2,P15,P30,Nf,Nc,epr,Ps30,phi,NRf,NRc,BPR,farB,htBleed,Nf_dmd,PCNf_dmd,W31,W32
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,21.61,554.36,2388.06,9046.19,1.3,47.47,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,21.61,553.75,2388.04,9044.07,1.3,47.49,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,21.61,554.26,2388.08,9052.94,1.3,47.27,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,21.61,554.45,2388.11,9049.48,1.3,47.13,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,21.61,554.00,2388.06,9055.15,1.3,47.28,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [3]:
df_train.set_index(['id_motore', 'ciclo'], verify_integrity=True)

/tmp/ipykernel_14163/3704896932.py:1: Pandas4Warning: The 'verify_integrity' keyword in DataFrame.set_index is deprecated and will be removed in a future version. Directly check the result.index.is_unique instead.
  df_train.set_index(['id_motore', 'ciclo'], verify_integrity=True)

                 altitudine  velocita_mach  manetta_tra      T2     T24  \
id_motore ciclo
1         1         -0.0007        -0.0004        100.0  518.67  641.82
          2          0.0019        -0.0003        100.0  518.67  642.15
          3         -0.0043         0.0003        100.0  518.67  642.35
          4          0.0007         0.0000        100.0  518.67  642.35
          5         -0.0019        -0.0002        100.0  518.67  642.37
...                     ...            ...          ...     ...     ...
100       196       -0.0004        -0.0003        100.0  518.67  643.49
          197       -0.0016        -0.0005        100.0  518.67  643.54
          198        0.0004         0.0000        100.0  518.67  643.42
          199       -0.0011         0.0003        100.0  518.67  643.23
          200       -0.0032        -0.0005        100.0  518.67  643.85

                     T30      T50     P2    P15     P30       Nf       Nc  \
id_motore ciclo
1         1      1589.70  1400.60  14.62  21.61  554.36  2388.06  9046.19
          2      1591.82  1403.14  14.62  21.61  553.75  2388.04  9044.07
          3      1587.99  1404.20  14.62  21.61  554.26  2388.08  9052.94
          4      1582.79  1401.87  14.62  21.61  554.45  2388.11  9049.48
          5      1582.85  1406.22  14.62  21.61  554.00  2388.06  9055.15
...                  ...      ...    ...    ...     ...      ...      ...
100       196    1597.98  1428.63  14.62  21.61  551.43  2388.19  9065.52
          197    1604.50  1433.58  14.62  21.61  550.86  2388.23  9065.11
          198    1602.46  1428.18  14.62  21.61  550.94  2388.24  9065.90
          199    1605.26  1426.53  14.62  21.61  550.68  2388.25  9073.72
          200    1600.38  1432.14  14.62  21.61  550.79  2388.26  9061.48

                 epr   Ps30     phi      NRf      NRc     BPR  farB  htBleed  \
id_motore ciclo
1         1      1.3  47.47  521.66  2388.02  8138.62  8.4195  0.03      392
          2      1.3  47.49  522.28  2388.07  8131.49  8.4318  0.03      392
          3      1.3  47.27  522.42  2388.03  8133.23  8.4178  0.03      390
          4      1.3  47.13  522.86  2388.08  8133.83  8.3682  0.03      392
          5      1.3  47.28  522.19  2388.04  8133.80  8.4294  0.03      393
...              ...    ...     ...      ...      ...     ...   ...      ...
100       196    1.3  48.07  519.49  2388.26  8137.60  8.4956  0.03      397
          197    1.3  48.04  519.68  2388.22  8136.50  8.5139  0.03      395
          198    1.3  48.09  520.01  2388.24  8141.05  8.5646  0.03      398
          199    1.3  48.39  519.67  2388.23  8139.29  8.5389  0.03      395
          200    1.3  48.20  519.30  2388.26  8137.33  8.5036  0.03      396

                 Nf_dmd  PCNf_dmd    W31      W32
id_motore ciclo
1         1        2388     100.0  39.06  23.4190
          2        2388     100.0  39.00  23.4236
          3        2388     100.0  38.95  23.3442
          4        2388     100.0  38.88  23.3739
          5        2388     100.0  38.90  23.4044
...                 ...       ...    ...      ...
100       196      2388     100.0  38.49  22.9735
          197      2388     100.0  38.30  23.1594
          198      2388     100.0  38.44  22.9333
          199      2388     100.0  38.29  23.0640
          200      2388     100.0  38.37  23.0522

[20631 rows x 24 columns]

In [4]:
df_train.describe()

,id_motore,ciclo,altitudine,velocita_mach,manetta_tra,T2,T24,T30,T50,P2,P15,P30,Nf,Nc,epr,Ps30,phi,NRf,NRc,BPR,farB,htBleed,Nf_dmd,PCNf_dmd,W31,W32
count,20631.000000,20631.000000,20631.000000,20631.000000,20631.0,20631.00,20631.000000,20631.000000,20631.000000,2.063100e+04,20631.000000,20631.000000,20631.000000,20631.000000,20631.0,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,2.063100e+04,20631.000000,20631.0,20631.0,20631.000000,20631.000000
mean,51.506568,108.807862,-0.000009,0.000002,100.0,518.67,642.680934,1590.523119,1408.933782,1.462000e+01,21.609803,553.367711,2388.096652,9065.242941,1.3,47.541168,521.413470,2388.096152,8143.752722,8.442146,3.000000e-02,393.210654,2388.0,100.0,38.816271,23.289705
std,29.227633,68.880990,0.002187,0.000293,0.0,0.00,0.500053,6.131150,9.000605,5.329200e-15,0.001389,0.885092,0.070985,22.082880,0.0,0.267087,0.737553,0.071919,19.076176,0.037505,3.469531e-18,1.548763,0.0,0.0,0.180746,0.108251
min,1.000000,1.000000,-0.008700,-0.000600,100.0,518.67,641.210000,1571.040000,1382.250000,1.462000e+01,21.600000,549.850000,2387.900000,9021.730000,1.3,46.850000,518.690000,2387.880000,8099.940000,8.324900,3.000000e-02,388.000000,2388.0,100.0,38.140000,22.894200
25%,26.000000,52.000000,-0.001500,-0.000200,100.0,518.67,642.325000,1586.260000,1402.360000,1.462000e+01,21.610000,552.810000,2388.050000,9053.100000,1.3,47.350000,520.960000,2388.040000,8133.245000,8.414900,3.000000e-02,392.000000,2388.0,100.0,38.700000,23.221800
50%,52.000000,104.000000,0.000000,0.000000,100.0,518.67,642.640000,1590.100000,1408.040000,1.462000e+01,21.610000,553.440000,2388.090000,9060.660000,1.3,47.510000,521.480000,2388.090000,8140.540000,8.438900,3.000000e-02,393.000000,2388.0,100.0,38.830000,23.297900
75%,77.000000,156.000000,0.001500,0.000300,100.0,518.67,643.000000,1594.380000,1414.555000,1.462000e+01,21.610000,554.010000,2388.140000,9069.420000,1.3,47.700000,521.950000,2388.140000,8148.310000,8.465600,3.000000e-02,394.000000,2388.0,100.0,38.950000,23.366800
max,100.000000,362.000000,0.008700,0.000600,100.0,518.67,644.530000,1616.910000,1441.490000,1.462000e+01,21.610000,556.060000,2388.560000,9244.590000,1.3,48.530000,523.380000,2388.560000,8293.720000,8.584800,3.000000e-02,400.000000,2388.0,100.0,39.430000,23.618400